import type { Metadata } from 'next'
import { Roboto } from 'next/font/google';
import '@/styles/globals.css';
import Header from "@/components/header"
import Footer from "@/components/footer"
import { AuthProvider } from "@/contexts/AuthContext";

const roboto = Roboto({
  subsets: ['latin'],
  display: 'swap',
  weight: ['400', '500', '700', '900'],
  variable: '--font-roboto',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${roboto.variable}`}>
        <div className="flex min-h-screen flex-col items-center justify-center bg-blue-light">
          <AuthProvider>
            <Header />
            <div className="flex-grow py-8 w-full px-4">
              {children}
            </div>
            <Footer />
          </AuthProvider>

        </div>
      </body>
    </html>
  )
}
